services:
  - type: web
    name: zaidan-fitness-record
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: zaidanfitnessgym@gmail.com
      - key: SMTP_PASSWORD
        sync: false
      - key: BACKUP_TO_EMAIL
        value: true
      - key: WHATSAPP_DEFAULT_COUNTRY_CODE
        value: 92
    disk:
      name: gym-data
      mountPath: /opt/render/project/src
      sizeGB: 1
